version: '3'

networks:
  home_networky:
services:
  mosquitto:
    image: eclipse-mosquitto:1.6.12
    container_name: mosquitto
    networks:
      - home_networky
    ports:
      - 1883:1883
    volumes:
      - ./01-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./01-mosquitto/users:/mosquitto/config/users
      - ${DATA_DIR}/mosquitto/data:/mosquitto/data
      - ${DATA_DIR}/mosquitto/log:/mosquitto/log
    restart: always

  influxdb:
    image: influxdb:1.7.10
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ${DATA_DIR}/influxdb:/var/lib/influxdb
    networks:
      - home_networky
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3001:3000
    volumes:
      - ${DATA_DIR}/grafana:/var/lib/grafana
    networks:
      - home_networky
    restart: always

  mqttbridge:
    build: ./02-bridge
    image: nilhcem/mqttbridge
    container_name: mqttbridge
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - home_networky
    restart: always
